In [229]:
import numpy as np

In [230]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,3,4))

In [231]:
data

array([[[0.55930516, 0.52293112, 0.70508433, 0.0050956 ],
        [0.47196621, 0.01295017, 0.58759326, 0.6210408 ],
        [0.84984129, 0.56855733, 0.03517758, 0.90170879]],

       [[0.25389308, 0.85070783, 0.82934147, 0.12063623],
        [0.62556186, 0.29701654, 0.10312515, 0.15427257],
        [0.97580872, 0.5364921 , 0.29734809, 0.88978377]]])

In [232]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [233]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [234]:
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [235]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [236]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [237]:
data

array([[[0.55930516, 0.52293112, 0.70508433, 0.0050956 ],
        [0.47196621, 0.01295017, 0.58759326, 0.6210408 ],
        [0.84984129, 0.56855733, 0.03517758, 0.90170879]],

       [[0.25389308, 0.85070783, 0.82934147, 0.12063623],
        [0.62556186, 0.29701654, 0.10312515, 0.15427257],
        [0.97580872, 0.5364921 , 0.29734809, 0.88978377]]])

In [238]:
#attributes
shape = data.shape
size = data.size
types = data.dtype

In [239]:
shape

(2, 3, 4)

In [240]:
size

24

In [241]:
types

dtype('float64')

In [242]:
# slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [243]:
arr

array([[0.55930516, 0.52293112, 0.70508433, 0.0050956 ],
       [0.47196621, 0.01295017, 0.58759326, 0.6210408 ],
       [0.84984129, 0.56855733, 0.03517758, 0.90170879]])

In [244]:
slicer

array([[[0.55930516, 0.52293112, 0.70508433, 0.0050956 ],
        [0.47196621, 0.01295017, 0.58759326, 0.6210408 ],
        [0.84984129, 0.56855733, 0.03517758, 0.90170879]],

       [[0.25389308, 0.85070783, 0.82934147, 0.12063623],
        [0.62556186, 0.29701654, 0.10312515, 0.15427257],
        [0.97580872, 0.5364921 , 0.29734809, 0.88978377]]])

In [245]:
reverse

array([[0.25389308, 0.85070783, 0.82934147, 0.12063623],
       [0.62556186, 0.29701654, 0.10312515, 0.15427257],
       [0.97580872, 0.5364921 , 0.29734809, 0.88978377]])

In [246]:
singlevel

0.5593051559714893

In [247]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [248]:
list1

array([0.26447646, 0.67953691, 0.26257311, 0.57660023, 0.6869894 ,
       0.00452935, 0.00374884, 0.78624568, 0.86068619, 0.12552516])

In [249]:
list2

array([0.46953332, 0.86859183, 0.9629199 , 0.66352839, 0.58916189,
       0.66402921, 0.41160549, 0.25303784, 0.39739531, 0.65441634])

In [250]:
#basic math
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [251]:
add

array([0.73400978, 1.54812874, 1.22549301, 1.24012862, 1.27615129,
       0.66855856, 0.41535433, 1.03928352, 1.2580815 , 0.77994149])

In [252]:
sub

array([-0.20505687, -0.18905492, -0.70034679, -0.08692816,  0.0978275 ,
       -0.65949986, -0.40785665,  0.53320784,  0.46329089, -0.52889118])

In [253]:
div

array([0.56327516, 0.7823432 , 0.27268427, 0.86899105, 1.1660452 ,
       0.00682101, 0.00910786, 3.10722572, 2.16581872, 0.19181238])

In [254]:
mult

array([0.12418051, 0.59024021, 0.25283687, 0.38259062, 0.40474797,
       0.00300762, 0.00154304, 0.19894991, 0.34203265, 0.08214571])

In [255]:
dot

2.382275136625851

In [256]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [257]:
sqrt

5.0

In [258]:
ab

2

In [259]:
power

128

In [260]:
log

3.2188758248682006

In [261]:
exp

array([ 7.3890561 , 20.08553692])

In [262]:
mins

0.0037488440159603176

In [263]:
maxs

0.8606861943693899

In [264]:
data

array([[[0.55930516, 0.52293112, 0.70508433, 0.0050956 ],
        [0.47196621, 0.01295017, 0.58759326, 0.6210408 ],
        [0.84984129, 0.56855733, 0.03517758, 0.90170879]],

       [[0.25389308, 0.85070783, 0.82934147, 0.12063623],
        [0.62556186, 0.29701654, 0.10312515, 0.15427257],
        [0.97580872, 0.5364921 , 0.29734809, 0.88978377]]])

In [265]:
data.sort()
data

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433],
        [0.01295017, 0.47196621, 0.58759326, 0.6210408 ],
        [0.03517758, 0.56855733, 0.84984129, 0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783],
        [0.10312515, 0.15427257, 0.29701654, 0.62556186],
        [0.29734809, 0.5364921 , 0.88978377, 0.97580872]]])

In [266]:
print(data.shape)

(2, 3, 4)


In [267]:
data = data.reshape((2,2,-1)) # -1 means that we do not care the last value of the shape and it gave 6 automatically

In [268]:
data.shape

(2, 2, 6)

In [269]:
data

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433, 0.01295017,
         0.47196621],
        [0.58759326, 0.6210408 , 0.03517758, 0.56855733, 0.84984129,
         0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783, 0.10312515,
         0.15427257],
        [0.29701654, 0.62556186, 0.29734809, 0.5364921 , 0.88978377,
         0.97580872]]])

In [270]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [271]:
zeroes = np.insert(zeroes, 2, 1) # position adn value
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [272]:
data

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433, 0.01295017,
         0.47196621],
        [0.58759326, 0.6210408 , 0.03517758, 0.56855733, 0.84984129,
         0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783, 0.10312515,
         0.15427257],
        [0.29701654, 0.62556186, 0.29734809, 0.5364921 , 0.88978377,
         0.97580872]]])

In [273]:
data.reshape(2,3,-1)

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433],
        [0.01295017, 0.47196621, 0.58759326, 0.6210408 ],
        [0.03517758, 0.56855733, 0.84984129, 0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783],
        [0.10312515, 0.15427257, 0.29701654, 0.62556186],
        [0.29734809, 0.5364921 , 0.88978377, 0.97580872]]])

In [328]:
data = data.reshape(2,3,-1)
data

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433],
        [0.01295017, 0.47196621, 0.58759326, 0.6210408 ],
        [0.03517758, 0.56855733, 0.84984129, 0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783],
        [0.10312515, 0.15427257, 0.29701654, 0.62556186],
        [0.29734809, 0.5364921 , 0.88978377, 0.97580872]]])

In [330]:
np.delete(data, 0, axis=1) # shape is 2,3,4 axis=1 means do the change in the 1st position(3)

array([[[0.01295017, 0.47196621, 0.58759326, 0.6210408 ],
        [0.03517758, 0.56855733, 0.84984129, 0.90170879]],

       [[0.10312515, 0.15427257, 0.29701654, 0.62556186],
        [0.29734809, 0.5364921 , 0.88978377, 0.97580872]]])

In [332]:
np.save("new_array", data)

In [334]:
test = np.load("new_array.npy")
test

array([[[0.0050956 , 0.52293112, 0.55930516, 0.70508433],
        [0.01295017, 0.47196621, 0.58759326, 0.6210408 ],
        [0.03517758, 0.56855733, 0.84984129, 0.90170879]],

       [[0.12063623, 0.25389308, 0.82934147, 0.85070783],
        [0.10312515, 0.15427257, 0.29701654, 0.62556186],
        [0.29734809, 0.5364921 , 0.88978377, 0.97580872]]])